name: Generator

on:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python #安装python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Update links #更新
      run: |
        python generator/main.py
    - name: Commit & Push
      uses: action-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'output'
        force: 'true'
        commit-message: 'Generate Json'
        author-name: github-actions[bot]
        author-email: github-actions[bot]@noreply.github.com
